/*
 * Demografic mark tool
 * Demografic mark tool API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Label'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Label'));
  } else {
    // Browser globals (root is window)
    if (!root.DemograficMarkTool) {
      root.DemograficMarkTool = {};
    }
    root.DemograficMarkTool.Author = factory(root.DemograficMarkTool.ApiClient, root.DemograficMarkTool.Label);
  }
}(this, function(ApiClient, Label) {
  'use strict';

  /**
   * The Author model module.
   * @module model/Author
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Author</code>.
   * @alias module:model/Author
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Author</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Author} obj Optional instance to populate.
   * @return {module:model/Author} The populated <code>Author</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('nickname'))
        obj.nickname = ApiClient.convertToType(data['nickname'], 'String');
      if (data.hasOwnProperty('avatar'))
        obj.avatar = ApiClient.convertToType(data['avatar'], 'String');
      if (data.hasOwnProperty('userLabel'))
        obj.userLabel = Label.constructFromObject(data['userLabel']);
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} nickname
   */
  exports.prototype.nickname = undefined;

  /**
   * @member {String} avatar
   */
  exports.prototype.avatar = undefined;

  /**
   * @member {module:model/Label} userLabel
   */
  exports.prototype.userLabel = undefined;

  return exports;

}));
