/*
 * Demografic mark tool
 * Demografic mark tool API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Author', 'model/AuthorPost', 'model/Label', 'model/Source', 'api/AuthorsApi', 'api/ServicesApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Author'), require('./model/AuthorPost'), require('./model/Label'), require('./model/Source'), require('./api/AuthorsApi'), require('./api/ServicesApi'));
  }
}(function(ApiClient, Author, AuthorPost, Label, Source, AuthorsApi, ServicesApi) {
  'use strict';

  /**
   * Demografic_mark_tool_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var DemograficMarkTool = require('index'); // See note below*.
   * var xxxSvc = new DemograficMarkTool.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new DemograficMarkTool.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new DemograficMarkTool.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new DemograficMarkTool.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Author model constructor.
     * @property {module:model/Author}
     */
    Author: Author,
    /**
     * The AuthorPost model constructor.
     * @property {module:model/AuthorPost}
     */
    AuthorPost: AuthorPost,
    /**
     * The Label model constructor.
     * @property {module:model/Label}
     */
    Label: Label,
    /**
     * The Source model constructor.
     * @property {module:model/Source}
     */
    Source: Source,
    /**
     * The AuthorsApi service constructor.
     * @property {module:api/AuthorsApi}
     */
    AuthorsApi: AuthorsApi,
    /**
     * The ServicesApi service constructor.
     * @property {module:api/ServicesApi}
     */
    ServicesApi: ServicesApi
  };

  return exports;
}));


var DemograficMarkTool = require('index'); // See note below*.
 var serviceApi = new DemograficMarkTool.ServiceApi();
serviceApi.getSources(function (error, data, response) {
  var superHeroes = data;
  populateHeader(superHeroes);
  showHeroes(superHeroes);
})